### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by blondie63** [gregertw/actingweb_firstapp#29]
Is there a particular reason you didn't use Firebase Auth?

**Comment by gregertw** [comment]
Apologies, for some strange reason I overlooked this issue. 
The way firebase auth is implemented in Flutter, it's a fairly tailored experience (and fairly easy to integrate). If you have your own microservices and don't rely only on firebase, you need to integrate auth into your app in a different way (a pattern that is more generic than firebase auth). I believe showing such a more generic pattern is more value in the long-run for professional use of Flutter (although using Firebase is simpler).
