### ISSUE TITLE
Can't Get Packages

### ISSUE THREAD

**Issue by Crypt0Graphic** [gregertw/actingweb_firstapp#3]
I downloaded code and tried to "flutter packages get" and "flutter pub get". I get this error:

Because first_app depends on flutter_auth0 from path which doesn't exist (could not find package flutter_auth0 at "../flutter-auth0"), version solving failed.
pub get failed (66)
exit code 66

ReadMe file can include how to install and run. :/

**Comment by gregertw** [comment]
Hi @Crypt0Graphic , yes, as you can see in the readme: The plugin flutter_auth0 is expected in the directory above (../), so check out https://github.com/gregertw/flutter-auth0 there.

**Comment by Crypt0Graphic** [comment]
> Hi @Crypt0Graphic , yes, as you can see in the readme: The plugin flutter_auth0 is expected in the directory above (../), so check out https://github.com/gregertw/flutter-auth0 there.

Sorry, my mistake. I read somewhere else i guess.

**Comment by blondie63** [comment]
> > Hi @Crypt0Graphic , yes, as you can see in the readme: The plugin flutter_auth0 is expected in the directory above (../), so check out https://github.com/gregertw/flutter-auth0 there.
> 
> Sorry, my mistake. I read somewhere else i guess.

Hi, how you have installed the plugin flutter_auth0 ?
