### ISSUE TITLE
Because test >=1.20.0 depends on test_api 0.4.9 and test >=1.19.4 <1.20.0 depends on test_api 0.4.8

### ISSUE THREAD

**Issue by dyardy** [gregertw/actingweb_firstapp#37]
Heads up with latest code in repo, seeing the following issue on pub get

_Running "flutter pub get" in PicApp2...                         
Because test >=1.20.0 depends on test_api 0.4.9 and test >=1.19.4 <1.20.0 depends on test_api 0.4.8, test >=1.19.4 requires test_api 0.4.8 or 0.4.9.
And because every version of flutter_test from sdk depends on test_api 0.4.3, flutter_test from sdk is incompatible with test >=1.19.4.
So, because first_app depends on both flutter_test from sdk and test ^1.19.5, version solving failed.
pub get failed (1; So, because first_app depends on both flutter_test from sdk and test ^1.19.5, version solving failed.)_

Reference : Possible resolutions...
https://stackoverflow.com/questions/70396969/how-can-i-use-flutter-test-from-sdk-and-the-package-test-what-version-of-test-u

**Comment by gregertw** [comment]
Thanks, @dyardy! Is this the master branch or the beta_channel?  Master has passed through codemagic clean build, and test_api resolves to 0.4.8 for me. Have you done flutter upgrade to the latest stable version? I'm unable to replicate your problem I'm afraid. You may also want to try flutter clean.

**Comment by dyardy** [comment]
This was the master branch.

[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19043.1526], locale en-US)
    • Flutter version 2.8.1 at c:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (9 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

I am doing flutter upgrade now 
Upgrading Flutter to 2.10.2 from 2.8.1 in c:\flutter...

This seemed to resolve this issue.  I did see some warnings when building about firebase auth api deprecated etc.  Should I be trying the beta channel?

**Comment by gregertw** [comment]
Then you are good! Some plugins do show some deprecation notices. Normally nothing to worry about.
