### ISSUE TITLE
Log in with Google ..results odd navigation?

### ISSUE THREAD

**Issue by dyardy** [gregertw/actingweb_firstapp#38]
I am using beta build and running with latest Flutter.

I am seeing this...
![image](https://user-images.githubusercontent.com/261526/154865532-2bc8683b-10eb-4216-8a87-4da184e823ba.png)

click login
![image](https://user-images.githubusercontent.com/261526/154865616-ffda7eec-4254-4e8b-89da-234235531781.png)

choosing my gmail account, navigates me to this 
![image](https://user-images.githubusercontent.com/261526/154865640-764ce66d-878d-4a3d-9f7f-7441fe3a4f67.png)

Seems like an odd experience and have yet to see the other screens by just logging in.  The master branch had the same issue as well.

**Comment by gregertw** [comment]
Looks like a problem with the redirect. This is explained in the README, but I see that can be improved, so I'll add a task. For production, the app needs to be set up with a new Google auth client that recognises your app as a client and that is configured with the correct redirect url (not the current one). Out of the box and without changing environment.dart with your new Google client and the redirect URLs, the redirect should work, but you are apparently not redirected correctly. You need to debug the connection between the app and Google in the browser. Look at what is configured for the authclient here https://github.com/gregertw/actingweb_firstapp/blob/6cd4d08f510d63cc7ea356cd8a038614f76ba3bf/lib/providers/auth.dart#L327
