### ISSUE TITLE
is it working ?

### ISSUE THREAD

**Issue by blondie63** [gregertw/actingweb_firstapp#4]
Hi, i've tried to run with last flutter v1.12.13+hotfix.6
but i've this err:
Running "flutter pub get" in actingweb_firstapp...              
Because first_app depends on flutter_auth0 from path which doesn't exist (could not find package flutter_auth0 at "../flutter-auth0"), version solving failed.
pub get failed (66; Because first_app depends on flutter_auth0 from path which doesn't exist (could not find package flutter_auth0 at "../flutter-auth0"), version solving failed.)
exit code 66

Some have tried ?

**Comment by gregertw** [comment]
From the readme:
The plugin flutter_auth0 is expected in the directory above (../), so check out https://github.com/gregertw/flutter-auth0 there. This app is configured to use io.actingweb.firstapp as app identifier. You can use this identifier for testing, but for your own app, you want to change this manually manually in android/app/build.gradle and android/app/src/main/AndroidManifest.xml for Android. For iOS, you should change the product bundle identifier in XCode (TODO).
